### ISSUE TITLE
Categoría veteranos

### ISSUE THREAD

**Issue by pxp9** [acmfi/ConcursoAoC2021#1]
Sugiero crear una categoría para veteranos :D

**Comment by Charly98cma** [comment]
Crear una categoría que no entra en el concurso no tiene mucho sentido, y complicaría la corrección y comprobaciones posteriores.

Tienes a tu disposición el [repo de ACM](https://github.com/acmfi/AdventCode) donde cualquiera puede subir sus soluciones.
